
logging:
  config: classpath:logback-spring.xml
server:
  port: 18085
spring:
  application:
    name: rpc-server

rpc:
  server:
      zk:
        #根节点
        root: /rpc
        #Zookeeper服务地址
        addr: 192.168.178.130:2181
        #链接超时时间
        timeout: 10000
  #Rpc通信端口->Netty端口
  network:
      port: 28888