server:
  port: 8081
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: rpc-client

rpc:
  client:
      zk:
        root: /rpc
        addr: 192.168.178.130:2181
        switch: true
        timeout: 10000
      api:
        package: demo.ocean.rpc.api
  cluster:
        strategy: polling